- name: "Install dependencies"
  become: true
  apt:
    name: ["unzip", "tar"]
    state: latest
    update_cache: yes
- name: "Copy artifact into the server"
  become: true
  copy:
    src: artifact.tar.gz
    dest: ~/home/ubuntu/
- name: "Print working directory"
  become: true
  shell: pwd
  register: command_output
- name: "Extract zipped artifact"
  become: true
  unarchive:
    src: ~/home/ubuntu/artifact.tar.gz
    dest: ~/home/ubuntu/
    remote_src: true
    validate_certs: true
- name: "Run app"
  become: true
  shell: |
    pm2 stop default
    pm2 start npm -- start
- debug:
    var: command_output.stdout_lines
