- name: "Install dependencies"
  become: true
  apt:
    name: ["unzip", "tar"]
    state: latest
    update_cache: yes
- name: "Copy artifact into the server"
  become: true
  copy:
    src: "artifact.tar.gz"
    dest: "~/"
- name: "Extract zipped artifact"
  become: true
  shell: |
    tar -xvzf ~/artifact.tar.gz
- name: "Run app"
  become: true
  shell: |
    pm2 delete all
    pm2 start npm -- start
  register: command_output
- debug:
    var: command_output.stdout_lines
